from const import luafile_path


def genLuafile(protos):
    fileContent = ""
    fileContent += ('--Generated By tools Do not Edit;\n'
                    'ProtocalType = {\n'
                    )

    for index in range(len(protos)):
        fileContent +='''    '''+ protos[index]+''' = "''' + str(index) + '''",\n'''
    fileContent += '}'
    fo = open(luafile_path, "wb")
    fo.write(fileContent.encode('utf-8'))
    fo.close()
