-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Base_pb')
local pb_table = {}

pb_table.ERRORSYN = protobuf.Descriptor();
pb_table.ERRORSYN_MSG_FIELD = protobuf.FieldDescriptor();

pb_table.ERRORSYN_MSG_FIELD.name = "msg"
pb_table.ERRORSYN_MSG_FIELD.full_name = ".com.xsk.game.common.proto.ErrorSyn.msg"
pb_table.ERRORSYN_MSG_FIELD.number = 1
pb_table.ERRORSYN_MSG_FIELD.index = 0
pb_table.ERRORSYN_MSG_FIELD.label = 1
pb_table.ERRORSYN_MSG_FIELD.has_default_value = false
pb_table.ERRORSYN_MSG_FIELD.default_value = ""
pb_table.ERRORSYN_MSG_FIELD.type = 9
pb_table.ERRORSYN_MSG_FIELD.cpp_type = 9

pb_table.ERRORSYN.name = "ErrorSyn"
pb_table.ERRORSYN.full_name = ".com.xsk.game.common.proto.ErrorSyn"
pb_table.ERRORSYN.nested_types = {}
pb_table.ERRORSYN.enum_types = {}
pb_table.ERRORSYN.fields = {pb_table.ERRORSYN_MSG_FIELD}
pb_table.ERRORSYN.is_extendable = false
pb_table.ERRORSYN.extensions = {}

ErrorSyn = protobuf.Message(pb_table.ERRORSYN)

