-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('BY_pb')
local pb_table = {}

pb_table.BYDESKINFO = protobuf.Descriptor();
pb_table.BYDESKUSERINFO = protobuf.Descriptor();

pb_table.BYDESKINFO.name = "BYDeskInfo"
pb_table.BYDESKINFO.full_name = ".com.xsk.game.common.proto.BYDeskInfo"
pb_table.BYDESKINFO.nested_types = {}
pb_table.BYDESKINFO.enum_types = {}
pb_table.BYDESKINFO.fields = {}
pb_table.BYDESKINFO.is_extendable = false
pb_table.BYDESKINFO.extensions = {}
pb_table.BYDESKUSERINFO.name = "BYDeskUserInfo"
pb_table.BYDESKUSERINFO.full_name = ".com.xsk.game.common.proto.BYDeskUserInfo"
pb_table.BYDESKUSERINFO.nested_types = {}
pb_table.BYDESKUSERINFO.enum_types = {}
pb_table.BYDESKUSERINFO.fields = {}
pb_table.BYDESKUSERINFO.is_extendable = false
pb_table.BYDESKUSERINFO.extensions = {}

BYDeskInfo = protobuf.Message(pb_table.BYDESKINFO)
BYDeskUserInfo = protobuf.Message(pb_table.BYDESKUSERINFO)

