-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('DDMJ_pb')
local pb_table = {}

pb_table.DDMJDESKINFO = protobuf.Descriptor();
pb_table.DDMJDESKUSERINFO = protobuf.Descriptor();

pb_table.DDMJDESKINFO.name = "DDMJDeskInfo"
pb_table.DDMJDESKINFO.full_name = ".com.xsk.game.common.proto.DDMJDeskInfo"
pb_table.DDMJDESKINFO.nested_types = {}
pb_table.DDMJDESKINFO.enum_types = {}
pb_table.DDMJDESKINFO.fields = {}
pb_table.DDMJDESKINFO.is_extendable = false
pb_table.DDMJDESKINFO.extensions = {}
pb_table.DDMJDESKUSERINFO.name = "DDMJDeskUserInfo"
pb_table.DDMJDESKUSERINFO.full_name = ".com.xsk.game.common.proto.DDMJDeskUserInfo"
pb_table.DDMJDESKUSERINFO.nested_types = {}
pb_table.DDMJDESKUSERINFO.enum_types = {}
pb_table.DDMJDESKUSERINFO.fields = {}
pb_table.DDMJDESKUSERINFO.is_extendable = false
pb_table.DDMJDESKUSERINFO.extensions = {}

DDMJDeskInfo = protobuf.Message(pb_table.DDMJDESKINFO)
DDMJDeskUserInfo = protobuf.Message(pb_table.DDMJDESKUSERINFO)

