-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('Rank_pb')
local pb_table = {}

pb_table.RANKREQUEST = protobuf.Descriptor();
pb_table.RANKREQUEST_GAMEID_FIELD = protobuf.FieldDescriptor();
pb_table.RANKREQUEST_TYPE_FIELD = protobuf.FieldDescriptor();
pb_table.RANKSYN = protobuf.Descriptor();
pb_table.RANKSYN_GAMEID_FIELD = protobuf.FieldDescriptor();
pb_table.RANKSYN_TYPE_FIELD = protobuf.FieldDescriptor();
pb_table.RANKSYN_RANKLIST_FIELD = protobuf.FieldDescriptor();
pb_table.RANKITEM = protobuf.Descriptor();
pb_table.RANKITEM_RANKNUM_FIELD = protobuf.FieldDescriptor();
pb_table.RANKITEM_USERID_FIELD = protobuf.FieldDescriptor();
pb_table.RANKITEM_CURRENCY_FIELD = protobuf.FieldDescriptor();
pb_table.RANKITEM_POINT_FIELD = protobuf.FieldDescriptor();
pb_table.CURRENCYITEM = protobuf.Descriptor();
pb_table.CURRENCYITEM_TYPE_FIELD = protobuf.FieldDescriptor();
pb_table.CURRENCYITEM_NUM_FIELD = protobuf.FieldDescriptor();

pb_table.RANKREQUEST_GAMEID_FIELD.name = "gameId"
pb_table.RANKREQUEST_GAMEID_FIELD.full_name = ".com.xsk.game.common.proto.RankRequest.gameId"
pb_table.RANKREQUEST_GAMEID_FIELD.number = 1
pb_table.RANKREQUEST_GAMEID_FIELD.index = 0
pb_table.RANKREQUEST_GAMEID_FIELD.label = 1
pb_table.RANKREQUEST_GAMEID_FIELD.has_default_value = false
pb_table.RANKREQUEST_GAMEID_FIELD.default_value = ""
pb_table.RANKREQUEST_GAMEID_FIELD.type = 9
pb_table.RANKREQUEST_GAMEID_FIELD.cpp_type = 9

pb_table.RANKREQUEST_TYPE_FIELD.name = "type"
pb_table.RANKREQUEST_TYPE_FIELD.full_name = ".com.xsk.game.common.proto.RankRequest.type"
pb_table.RANKREQUEST_TYPE_FIELD.number = 2
pb_table.RANKREQUEST_TYPE_FIELD.index = 1
pb_table.RANKREQUEST_TYPE_FIELD.label = 1
pb_table.RANKREQUEST_TYPE_FIELD.has_default_value = false
pb_table.RANKREQUEST_TYPE_FIELD.default_value = 0
pb_table.RANKREQUEST_TYPE_FIELD.type = 5
pb_table.RANKREQUEST_TYPE_FIELD.cpp_type = 1

pb_table.RANKREQUEST.name = "RankRequest"
pb_table.RANKREQUEST.full_name = ".com.xsk.game.common.proto.RankRequest"
pb_table.RANKREQUEST.nested_types = {}
pb_table.RANKREQUEST.enum_types = {}
pb_table.RANKREQUEST.fields = {pb_table.RANKREQUEST_GAMEID_FIELD, pb_table.RANKREQUEST_TYPE_FIELD}
pb_table.RANKREQUEST.is_extendable = false
pb_table.RANKREQUEST.extensions = {}
pb_table.RANKSYN_GAMEID_FIELD.name = "gameid"
pb_table.RANKSYN_GAMEID_FIELD.full_name = ".com.xsk.game.common.proto.RankSyn.gameid"
pb_table.RANKSYN_GAMEID_FIELD.number = 1
pb_table.RANKSYN_GAMEID_FIELD.index = 0
pb_table.RANKSYN_GAMEID_FIELD.label = 1
pb_table.RANKSYN_GAMEID_FIELD.has_default_value = false
pb_table.RANKSYN_GAMEID_FIELD.default_value = ""
pb_table.RANKSYN_GAMEID_FIELD.type = 9
pb_table.RANKSYN_GAMEID_FIELD.cpp_type = 9

pb_table.RANKSYN_TYPE_FIELD.name = "type"
pb_table.RANKSYN_TYPE_FIELD.full_name = ".com.xsk.game.common.proto.RankSyn.type"
pb_table.RANKSYN_TYPE_FIELD.number = 2
pb_table.RANKSYN_TYPE_FIELD.index = 1
pb_table.RANKSYN_TYPE_FIELD.label = 1
pb_table.RANKSYN_TYPE_FIELD.has_default_value = false
pb_table.RANKSYN_TYPE_FIELD.default_value = 0
pb_table.RANKSYN_TYPE_FIELD.type = 5
pb_table.RANKSYN_TYPE_FIELD.cpp_type = 1

pb_table.RANKSYN_RANKLIST_FIELD.name = "rankList"
pb_table.RANKSYN_RANKLIST_FIELD.full_name = ".com.xsk.game.common.proto.RankSyn.rankList"
pb_table.RANKSYN_RANKLIST_FIELD.number = 3
pb_table.RANKSYN_RANKLIST_FIELD.index = 2
pb_table.RANKSYN_RANKLIST_FIELD.label = 3
pb_table.RANKSYN_RANKLIST_FIELD.has_default_value = false
pb_table.RANKSYN_RANKLIST_FIELD.default_value = {}
pb_table.RANKSYN_RANKLIST_FIELD.message_type = _RANKITEM
pb_table.RANKSYN_RANKLIST_FIELD.type = 11
pb_table.RANKSYN_RANKLIST_FIELD.cpp_type = 10

pb_table.RANKSYN.name = "RankSyn"
pb_table.RANKSYN.full_name = ".com.xsk.game.common.proto.RankSyn"
pb_table.RANKSYN.nested_types = {}
pb_table.RANKSYN.enum_types = {}
pb_table.RANKSYN.fields = {pb_table.RANKSYN_GAMEID_FIELD, pb_table.RANKSYN_TYPE_FIELD, pb_table.RANKSYN_RANKLIST_FIELD}
pb_table.RANKSYN.is_extendable = false
pb_table.RANKSYN.extensions = {}
pb_table.RANKITEM_RANKNUM_FIELD.name = "rankNum"
pb_table.RANKITEM_RANKNUM_FIELD.full_name = ".com.xsk.game.common.proto.RankItem.rankNum"
pb_table.RANKITEM_RANKNUM_FIELD.number = 1
pb_table.RANKITEM_RANKNUM_FIELD.index = 0
pb_table.RANKITEM_RANKNUM_FIELD.label = 1
pb_table.RANKITEM_RANKNUM_FIELD.has_default_value = false
pb_table.RANKITEM_RANKNUM_FIELD.default_value = 0
pb_table.RANKITEM_RANKNUM_FIELD.type = 5
pb_table.RANKITEM_RANKNUM_FIELD.cpp_type = 1

pb_table.RANKITEM_USERID_FIELD.name = "userId"
pb_table.RANKITEM_USERID_FIELD.full_name = ".com.xsk.game.common.proto.RankItem.userId"
pb_table.RANKITEM_USERID_FIELD.number = 2
pb_table.RANKITEM_USERID_FIELD.index = 1
pb_table.RANKITEM_USERID_FIELD.label = 1
pb_table.RANKITEM_USERID_FIELD.has_default_value = false
pb_table.RANKITEM_USERID_FIELD.default_value = 0
pb_table.RANKITEM_USERID_FIELD.type = 3
pb_table.RANKITEM_USERID_FIELD.cpp_type = 2

pb_table.RANKITEM_CURRENCY_FIELD.name = "currency"
pb_table.RANKITEM_CURRENCY_FIELD.full_name = ".com.xsk.game.common.proto.RankItem.currency"
pb_table.RANKITEM_CURRENCY_FIELD.number = 3
pb_table.RANKITEM_CURRENCY_FIELD.index = 2
pb_table.RANKITEM_CURRENCY_FIELD.label = 3
pb_table.RANKITEM_CURRENCY_FIELD.has_default_value = false
pb_table.RANKITEM_CURRENCY_FIELD.default_value = {}
pb_table.RANKITEM_CURRENCY_FIELD.message_type = _CURRENCYITEM
pb_table.RANKITEM_CURRENCY_FIELD.type = 11
pb_table.RANKITEM_CURRENCY_FIELD.cpp_type = 10

pb_table.RANKITEM_POINT_FIELD.name = "point"
pb_table.RANKITEM_POINT_FIELD.full_name = ".com.xsk.game.common.proto.RankItem.point"
pb_table.RANKITEM_POINT_FIELD.number = 4
pb_table.RANKITEM_POINT_FIELD.index = 3
pb_table.RANKITEM_POINT_FIELD.label = 1
pb_table.RANKITEM_POINT_FIELD.has_default_value = false
pb_table.RANKITEM_POINT_FIELD.default_value = 0
pb_table.RANKITEM_POINT_FIELD.type = 3
pb_table.RANKITEM_POINT_FIELD.cpp_type = 2

pb_table.RANKITEM.name = "RankItem"
pb_table.RANKITEM.full_name = ".com.xsk.game.common.proto.RankItem"
pb_table.RANKITEM.nested_types = {}
pb_table.RANKITEM.enum_types = {}
pb_table.RANKITEM.fields = {pb_table.RANKITEM_RANKNUM_FIELD, pb_table.RANKITEM_USERID_FIELD, pb_table.RANKITEM_CURRENCY_FIELD, pb_table.RANKITEM_POINT_FIELD}
pb_table.RANKITEM.is_extendable = false
pb_table.RANKITEM.extensions = {}
pb_table.CURRENCYITEM_TYPE_FIELD.name = "type"
pb_table.CURRENCYITEM_TYPE_FIELD.full_name = ".com.xsk.game.common.proto.currencyItem.type"
pb_table.CURRENCYITEM_TYPE_FIELD.number = 1
pb_table.CURRENCYITEM_TYPE_FIELD.index = 0
pb_table.CURRENCYITEM_TYPE_FIELD.label = 1
pb_table.CURRENCYITEM_TYPE_FIELD.has_default_value = false
pb_table.CURRENCYITEM_TYPE_FIELD.default_value = 0
pb_table.CURRENCYITEM_TYPE_FIELD.type = 5
pb_table.CURRENCYITEM_TYPE_FIELD.cpp_type = 1

pb_table.CURRENCYITEM_NUM_FIELD.name = "num"
pb_table.CURRENCYITEM_NUM_FIELD.full_name = ".com.xsk.game.common.proto.currencyItem.num"
pb_table.CURRENCYITEM_NUM_FIELD.number = 2
pb_table.CURRENCYITEM_NUM_FIELD.index = 1
pb_table.CURRENCYITEM_NUM_FIELD.label = 1
pb_table.CURRENCYITEM_NUM_FIELD.has_default_value = false
pb_table.CURRENCYITEM_NUM_FIELD.default_value = 0
pb_table.CURRENCYITEM_NUM_FIELD.type = 3
pb_table.CURRENCYITEM_NUM_FIELD.cpp_type = 2

pb_table.CURRENCYITEM.name = "currencyItem"
pb_table.CURRENCYITEM.full_name = ".com.xsk.game.common.proto.currencyItem"
pb_table.CURRENCYITEM.nested_types = {}
pb_table.CURRENCYITEM.enum_types = {}
pb_table.CURRENCYITEM.fields = {pb_table.CURRENCYITEM_TYPE_FIELD, pb_table.CURRENCYITEM_NUM_FIELD}
pb_table.CURRENCYITEM.is_extendable = false
pb_table.CURRENCYITEM.extensions = {}

RankItem = protobuf.Message(pb_table.RANKITEM)
RankRequest = protobuf.Message(pb_table.RANKREQUEST)
RankSyn = protobuf.Message(pb_table.RANKSYN)
currencyItem = protobuf.Message(pb_table.CURRENCYITEM)

